### ISSUE TITLE
GitHub Environment Secrets/Variables not working

### ISSUE THREAD

**Issue by iuritorres** [iuritorres/googlesheets-financial-rpa#1]
# My GitHub Environment secrets and variables are not more available in my code.

Yesterday, i tried it and it was working, how you can see in [#15 workflow run](https://github.com/iuritorres/googlesheets-financial-rpa/actions/runs/6540034496/job/17759225035), in "run-program" job, at the "Run main file" step.

But today, I'm trying with the same ways but it isn't working at all, you can see this in my [#64 workflow run](https://github.com/iuritorres/googlesheets-financial-rpa/actions/runs/6568894023/job/17843965718), in build-and-run job, at the same step, it is returning "AQUI: None", this "None" should be my environment variable value.

## Into my GitHub Environment "TEST"
![image](https://github.com/iuritorres/googlesheets-financial-rpa/assets/104526359/f265005d-6a44-4991-80b4-e8e7ca95c0b5)

## My workflow file:
```yml
name: Execute Financial Google Sheets RPA
run-name: Initializing Data Manipulation 📊

on:
  push:
    branches:
      - main

  # schedule:
  #   - cron: '*/5 * * * *'

permissions:
  contents: write
  packages: read

jobs:
  collecting-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Displaying job's informations
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 This is running in branch ${{ github.ref }}, in repository ${{ github.repository }}."
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Display job's status
        run: echo "🍏 This job's status is ${{ job.status }}."

  build-and-run:
    runs-on: ubuntu-latest

    environment: TEST
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TEST: ${{ vars.TEST }}

    steps:
      # Build
      - name: Check out repository code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Setup environment
        run: |
          sudo python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install -r requirements.txt --ignore-installed pyasn1-modules

      - name: Display projects info
        run: |
          sudo python3 -c "import sys; print(sys.version); print(sys.path)"
          sudo python3 -m pip freeze

      # Run
      - name: Run main file 
        run: sudo python3 src/main.py
```

My python code you can check in my [repository code](https://github.com/iuritorres/googlesheets-financial-rpa/tree/main/src), i activate the[ main.py](https://github.com/iuritorres/googlesheets-financial-rpa/blob/main/src/main.py) file, but it's calling environment in [GoogleSheets.py](https://github.com/iuritorres/googlesheets-financial-rpa/blob/main/src/GoogleSheet.py)

I tried to set, "env: and "envrionment" workflow's parameter outside "jobs", inside "jobs", inside a specific job, inside a specific step, and none of those worked...

Someone can help me this?
Thank you.
